// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqiheriagktsyeuxsugb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxaWhlcmlhZ2t0c3lldXhzdWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDc0MzAsImV4cCI6MjA2OTEyMzQzMH0.JrmD7mhA3k3OMXQ5t2fi617zh79X_N2AKz5jD7f9bco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});